#Maximum storeage capacity in MB
storageCapacity: 1200000
#DataOne Coordinating Node, required by replication and acess control services
coordinatingNodeUrl: https://cn-stage.test.dataone.org/
#Member Node description, used for the Capabilities request
#https://releases.dataone.org/online/api-documentation-v2.0/apis/MN_APIs.html#MNCore.getCapabilities
node:
 name: "GBIFS Member Node"
 description: "GBIFS DataOne Member Node"
 baseURL: "https://labs.gbif.org:7005/mn/v1/"
 subject: [ {value: "CN=GBIFS Test Member Node"} ]
 identifier:
   value: "urn:node:mnTestGBIF"
 contactSubject: [value: "CN=Informatics, DC=GBIFS, DC=org"]
 services:
   service: [
       {available: true, name: "MNCore", version: "v1"},
       {available: true, name: "MNRead", version: "v1"},
       {available: true, name: "MNAuthorization", version: "v1"},
       {available: true, name: "MNStorage", version: "v1"},
       {available: true, name: "MNReplication", version: "v1"}
   ]

#Defaults port can be overriden
server:
 applicationConnectors:
    - type: http
      port: 8082
    - type: https
      port: 8443
      keyStorePath: conf/certificates/serverkeystore.jks
      keyStoreType: JKS
      keyStorePassword: password
      trustStorePath: conf/certificates/servertruststore.jks
      trustStorePassword: password
      trustStoreType: JKS
      #client certificates are wanted but not needed by all the endpoints
      needClientAuth: false
      wantClientAuth: true
      allowRenegotiation: true
      validateCerts: true
      #Some DataOne issued certificates fail the peer validation
      validatePeers: false
 adminConnectors:
     - type: http
       port: 8083
#Jersey client configuration, used to create secure/trusted connections against other DataOne nodes
jerseyClient:
  timeout: 2000ms
  connectionTimeout: 2000ms
  tls:
    verifyHostname: true
    #Only the client certificate provided by DataOne must go in this store
    keyStorePath: conf/certificates/clientkeystore.jks
    keyStoreType: JKS
    keyStorePassword: password
    #The provided client certificate and Coordinating Nodes certificates go in this store
    trustStorePath: conf/certificates/clienttruststore.jks
    trustStoreType: JKS
    trustStorePassword: password
    trustSelfSignedCertificates: false
